"""empty message

Revision ID: 836d6aaf6d75
Revises: e5b02266a46b
Create Date: 2020-11-10 16:28:24.335832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '836d6aaf6d75'
down_revision = 'e5b02266a46b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('user_name', sa.String(length=255), nullable=True))
    op.drop_constraint('task_ibfk_1', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'user', ['user_name'], ['username'])
    op.drop_column('task', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('user_id', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_ibfk_1', 'task', 'user', ['user_id'], ['username'])
    op.drop_column('task', 'user_name')
    # ### end Alembic commands ###
